<?php

namespace App\Http\Controllers;

use App\DatePresenter;
use App\Meals\MealShoppingList;
use App\Purchases\ShoppingList;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class MealShoppingListPdfController extends Controller
{
    public function show(MealShoppingList $list)
    {
        $title = "Ad-hoc Shopping List #{$list->id}";

        $subtitle = sprintf(
            "Generated by %s on %s, %s",
            request()->user()->name,
            now()->format('l'),
            DatePresenter::pretty(now())
        );

        $path = ShoppingList::fromMealShoppingList($list)
            ->saveAsPdf(
                file_name: Str::random(8) . ".pdf",
                title: $title,
                subtitle: $subtitle,
            );

        return Storage::disk('admin_stuff')->download($path);
    }
}
